### PR TITLE
Improved primality testing

### PR DESCRIPTION
**Pull request by ryco117**
I've added a function, `prob_is_prime()`, for performing probablistic primality testing (Miller-Rabin) when the input is sufficiently large. It calls `is_prime()` for small inputs. Note that the probability of error is `4**-count`. I have not switched the internal code to call this new function (because I assume all internally needed primes are fairly small) but I think it's important for at least the math library to test primality quickly for large inputs.

### CODE REVIEW

**Comment by ryco117** [comment]
Well there were a few problems with that, but its working now.

**Comment by CoffeeTableEspresso** [comment]
I'm not sure if we need this? At the very least we should look into how big we expect the tables to get before we add this in. 

For the math library, I was planning on excluding prime focused stuff and keeping it very focused on stuff that would be widely needed, like trig functions and such. (My plan is for the standard libraries to only include stuff that everyone / almost everyone would need, and I'm not sure primes fall under that.)

**Comment by ryco117** [comment]
I don' t think there's any harm in having **a** isprime function in the std-math (since we need this functionality anyway for our hashtables). The question is whether the probablistic primality test is overkill or not (imo). 

I'd like the math library to support lcm, gcd, and the primality test since I think they are useful building blocks for more complex number-theoretic operations (which it'd be nice to be able to script with some speed). 

Ultimately your say but that was my reasoning.

**Comment by CoffeeTableEspresso** [comment]
alright that's fair enough. It won't take up too much extra space since I have it already. I just don't want to keep adding stuff to YASL. I/m trying to keep it as small as possible.

**Comment by CoffeeTableEspresso** [comment]
what sort of number theoretic stuff are you planning on doing with YASL though?

**Comment by CoffeeTableEspresso** [comment]
I don't think `isprime` is useful enough for the average user to warrant including it in the standard library. YASL will probably never be _the_ numerical library of people's choice anyways, it's more designed for embedding in C/C++ applications.

If in the future there's a good use case for prime checkers that's widely applicable to lots of people, I'd consider adding it back. otherwise people can use their own implementation (C or YASL) or a 3rd party lib.

**Comment by CoffeeTableEspresso** [comment]
actually fuck it this is going in

**Comment by CoffeeTableEspresso** [comment]
I'll deal with any issues later

**Comment by ryco117** [comment]
Lol, you really don't need to include the number theory stuff if you don't want.

**Comment by CoffeeTableEspresso** [comment]
it's totally fine. I'm looking towards the future now lol.

I wanna add a bit more stuff then do the v0.3.4 release.

**Comment by CoffeeTableEspresso** [comment]
basically once I'm done a lot of stuff from my list of desired features then I'll do a "state of YASL" review and see where it's at

**Comment by CoffeeTableEspresso** [comment]
you wanna help me with more stuff? planned or things you think YASL needs.

**Comment by ryco117** [comment]
Yeah of course. Add "help wanted" tags under yasl-enhancements and I'll see

**Comment by CoffeeTableEspresso** [comment]
off the top of my head: any of the libraries described in YASL enhancements, underscores in numeric literals, exponential notation for numbers, `s[a:b]` notation for slices, all are good to go into the next release and should be pretty well described. I can add issues or more details if needed for any of them. 

I also want to do some internal changes needed to set up some of the other enhancements in later releases.

**Pull request merged**
