### PR TITLE
issue #94 add relative pathes to include directives

### PR DESCRIPTION
**Pull request by gadget114514**
In order to reduce # of include dir, change #include path

### CODE REVIEW

**Comment by CoffeeTableEspresso** [comment]
This broke the build. If you fix this I can merge it in. 

You might want to try merging this into the v0.3.5 branch instead, since on there I've moved `math` and `io` to the main repo (on master they are submodules right now). It will probably be easier to do these changes when you don't have to deal with submodules.

Thanks :)

**Comment by gadget114514** [comment]
it is difficult to treat submodules in merging. i can succeed in catching up with upstream except submodule.

**Comment by gadget114514** [comment]
change version.

**Comment by CoffeeTableEspresso** [comment]
Yes I understand it's hard to catch up the submodules. However, i plan to remove the submodules in the next release. 

So if you do these changes on the v0.3.5 branch instead of master, you won't have any issues with submodules. And then once im done with that release everything will be merged into master

**Pull request closed without merging**
